### ISSUE TITLE
0xDetermination - Protocol will be bricked on zkSync due to `computePoolAddress()` calculation

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-02-leverage-contracts-judging#35]
0xDetermination

medium

# Protocol will be bricked on zkSync due to `computePoolAddress()` calculation

## Summary
`computePoolAddress()` bricks the protocol on zkSync.
## Vulnerability Detail
`computePoolAddress()` works for all EVM-compatible L2s, but zkSync is not really EVM-compatible. It uses a different method to calculate contract addresses (https://docs.zksync.io/build/developer-reference/differences-with-ethereum.html#create-create2). 
## Impact
Protocol won't function on zkSync.
## Code Snippet
https://github.com/sherlock-audit/2024-02-leverage-contracts/blob/main/wagmi-leverage/contracts/abstract/ApproveSwapAndPay.sol#L251
## Tool used

Manual Review

## Recommendation
Refactor `computePoolAddress()` to be compatible with zkSync or create a different contract for zkSync.

**Comment by fann95** [comment]
I have already answered in the previous audit. If we deploy to zkSync then the appropriate corrections will be made. Without them, the contract will not work.There is no bug or vulnerability here.
