### ISSUE TITLE
0xDetermination - Entrance fee contributes to min fee; if the protocol intends for the min fee to be collected on top of the entrance fee, then the min fee may not be collected

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-02-leverage-contracts-judging#45]
0xDetermination

medium

# Entrance fee contributes to min fee; if the protocol intends for the min fee to be collected on top of the entrance fee, then the min fee may not be collected

## Summary
If the entrance fee is meant to be collected on top of a minimum fee, then the min fee is not enforced properly.
## Vulnerability Detail
We can see in this line of code that the entrance fee is added to the borrower's fees when a new loan is taken: https://github.com/sherlock-audit/2024-02-leverage-contracts/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L1036

Then when `repay()` is called, a min fee is enforced based on the borrower's fees:
```solidity
            if (collateralBalance > 0) {
                uint256 compensation = _calcFeeCompensationUpToMin(
                    collateralBalance,
                    currentFees,
                    borrowing.feesOwed
                );
                currentFees += compensation;
```
```solidity
    function _calcFeeCompensationUpToMin(
        int256 collateralBalance,
        uint256 currentFees,
        uint256 feesOwed
    ) private pure returns (uint256 compensation) {
        uint256 minimum = Constants.MINIMUM_AMOUNT * Constants.COLLATERAL_BALANCE_PRECISION;
        uint256 total = currentFees + feesOwed;
        if (total < minimum) {
            compensation = minimum - total;
            if (uint256(collateralBalance) < compensation) {
                compensation = uint256(collateralBalance);
            }
        }
    }
```
This may cause the min fee to not be collected, if the min fee of `Constants.MINIMUM_AMOUNT` is meant to be collected on top of the entrance fee.

Note that the borrower's `collateralBalance` will always be greater than or equal to the min fee when taking out a loan (https://github.com/sherlock-audit/2024-02-leverage-contracts/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L943-L945).
## Impact
Min fee might not be collected if the entrance fee is meant to be collected on top of the min fee.
## Code Snippet
https://github.com/sherlock-audit/2024-02-leverage-contracts/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L617-L623
https://github.com/sherlock-audit/2024-02-leverage-contracts/blob/main/wagmi-leverage/contracts/LiquidityBorrowingManager.sol#L758-L771
## Tool used

Manual Review

## Recommendation
If desired, include the entrance fee in the min fee calculation in `repay()`.

Duplicate of #37

**Comment by fann95** [comment]
The minimum payment was intended as a roundup and does not play any role in the protocol...it is currently removed from the code
